title: "Luis Espath"
author: "Luis Espath"
email: "luis.espath@nottingham.ac.uk"
description: "Assistant Professor of Applied Mathematics"
baseurl: "" # important for GitHub Pages on espath.github.io
url: "https://espath.github.io"
github_username: espath
google_scholar: https://scholar.google.com/citations?user=5DOQcG8AAAAJ&hl=en

# Use Minimal Mistakes theme via GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes"

# Enable custom collections
collections:
  pages:
    output: true
    permalink: /:path/

# Set default layout for pages
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Navigation menu
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
  - title: "Teaching"
    url: /teaching/
  - title: "Book"
    url: /book/

markdown: kramdown